CREATE DATABASE RESERVATION

USE RESERVATION


CREATE TABLE USER 
(
ID number(10) NOT NULL,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
EMAIL VARCHAR(20),
PASSWORD VARCHAR(256), 
PRIMARY KEY (ID),
UNIQUE KEY (EMAIL)
)
ALTER TABLE USER_INFO ADD PRIMARY KEY(ID);
ALTER TABLE USER_INFO ADD CONSTRAINT EMIAL_CONS  UNIQUE (EMAIL);



CREATE TABLE FLIGHT
(
  ID number(10)  NOT NULL,
  FLIGHT_NUMBER VARCHAR(20)  NOT NULL, 
  OPERATING_AIRLINES VARCHAR(20)  NOT NULL,
  DEPARTURE_CITY VARCHAR(20)  NOT NULL,
  ARRIVAL_CITY VARCHAR(20)  NOT NULL,
  DATE_OF_DEPARTURE DATE  NOT NULL,
  ESTIMATED_DEPARTURE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
  PRIMARY KEY (ID)
);
/
CREATE TABLE PASSENGER
(
  ID number(10) NOT NULL,
  FIRST_NAME       VARCHAR(256),
  LAST_NAME    VARCHAR(256),
  MIDDLE_NAME   VARCHAR(256),
  EMAIL VARCHAR(50),
  PHONE VARCHAR(10),
  PRIMARY KEY (ID)
);

CREATE TABLE RESERVATION
(
  ID number(10) NOT NULL,
  CHECKED_IN number(10),
  NUMBER_OF_BAGS number(10),
  PASSENGER_ID number(10),
  FLIGHT_ID number(10),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID),
  FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID)
);

SELECT * FROM USER

SELECT * FROM PASSENGER 

SELECT * FROM FLIGHT

SELECT * FROM RESERVATION



DROP TABLE USER
DROP TABLE RESERVATION
DROP TABLE PASSENGER
DROP TABLE FLIGHT

DROP DATABASE RESERVATION

@mappedsuperclass

